flowchart TD 
    A[Flow1455] -->|event| Action1(Action 1)
    click Action1 "../actions/action1.mmd" "Open Action 1"

    Action1 --> Action2(Action 2)
    click Action2 "../actions/action2.mmd" "Open Action 2"